### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by FirefoxSRV** [FirefoxSRV/Match-da-pairs#5]
- [ ] Create `CONTRIBUTING.md`.
- [ ] Create `CODE_OF_CONDUCT.md`
- [ ] Create `SECURITY.md`.
- [ ] Make sure all of them are in `/docs` folder.

**Comment by BIJJUDAMA** [comment]
@FirefoxSRV I would like to take this issue

**Comment by FirefoxSRV** [comment]
Sure, assigning this to you...Good luck

**Comment by FirefoxSRV** [comment]
Good luck

**Comment by BIJJUDAMA** [comment]
@FirefoxSRV Can I please get your email to add as contact information in the files

**Comment by FirefoxSRV** [comment]
Sure, my email is: shreyasvisweshwaran@gmail.com

**Comment by BIJJUDAMA** [comment]
Uhh so @FirefoxSRV 
<img width="448" alt="Screenshot 2024-12-23 135003" src="https://github.com/user-attachments/assets/f86eee7b-c247-4c43-bbad-06810dd57a0b" />
For this code of conduct. I am adding that as part of CONTRIBUTING.md
But since code of conduct only exists in the repository I have forked, I won't be able to link it

So how about I put a pull request and you can check the SECURITY.md and CODE_OF_CONDUCT.md files and then merge them.
After that I use their links and add them to CONTRIBUTING.md and make a final pull request which you can review and if everythings all right you can merge it for the last time

Please lmk if this is fine or should I change the content of CONTRIBUTING.md

**Comment by FirefoxSRV** [comment]
Yes sure, go ahead

**Comment by FirefoxSRV** [comment]
Update. Create a new PR for the updated Contributing.md .......With the updates done, u will be awarded another 10 points for your work !

**Comment by BIJJUDAMA** [comment]
@FirefoxSRV Review please
I see that my pr hasn't been merged

**Comment by FirefoxSRV** [comment]
Yes, had to check them

**Comment by FirefoxSRV** [comment]
Thank you @BIJJUDAMA
